import {StyleSheet} from 'react-native';

export const homeStyles = StyleSheet.create({
  countainer: {
    height: '100%',
  },
  header: {
    padding: 16,
    backgroundColor: '#fff',
    elevation: 1,
    marginHorizontal: 16,
    marginTop: 16,
  },
  text: {
    color: '#01020D',
    fontSize: 18,
    fontWeight: '700',
    marginRight: 8,
  },
  balance: {
    fontWeight: '400',
    fontSize: 13,
    color: '#0B1596',
    marginTop: 24,
  },
  basedOn: {
    fontSize: 14,
    fontWeight: '400',
    color: '#9b9b9b',
  },
  BObtn: {
    backgroundColor: '#F8F9F9',
    padding: 8,
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
  },
  amount: {
    fontWeight: '500',
    fontSize: 18,
    color: '#01020D',
  },
  records: {
    backgroundColor: '#fff',
    elevation: 1,
    marginTop: 16,
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 8,
  },
  searchInput: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginRight: 16,
  },
  tcl: {
    display: 'flex',
    flexDirection: 'row',
    marginHorizontal: 8,
  },
  remainInput: {
    paddingHorizontal: 16,
    height: 50,
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 5,
    marginTop: 8,
  },
  remainInput2: {
    paddingHorizontal: 16,
    height: 50,
    width: '50%',
    backgroundColor: '#ffffff',
    marginTop: 8,
    paddingVertical: 8,
  },
  filterIcon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fafafa',
    width: 50,
    height: 50,
    borderRadius: 50,
    marginHorizontal: 8,
    marginVertical: 8,
  },
  btn: {
    backgroundColor: '#0B1596',
    padding: 16,
    position: 'absolute',
    top: '87%',
    borderRadius: 29,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 2,
    alignSelf: 'center',
  },
  search: {
    backgroundColor: '#fff',
    borderRadius: 50,
    width: '80%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    height: '80%',
    paddingLeft: 8,
  },
});
