import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  headerText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#01020D',
  },
  subHeader: {
    fontSize: 14,
    fontWeight: '400',
    color: '#9b9b9b',
    marginTop: 16,
  },
  textInput: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#949494',
    fontSize: 16,
    zIndex: 1,
    flex: 1,
  },
  container: {
    height: '100%',
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingTop: 24,
    display: 'flex',
    justifyContent: 'space-between',
    paddingBottom:24
  },
  text: {
    fontSize: 10,
    marginTop: 4,
    marginBottom: 16,
    marginLeft: 8,
    alignSelf: 'flex-end',
  },
  btn: {
    borderRadius: 5,
    paddingHorizontal: 56,
    paddingVertical: 8,
    backgroundColor: '#152F8C',
  },
  tar: {
    color: '#1616E7',
    marginRight: 32,
  },
  phoneNumber: {
    fontSize: 12,
    color: '#334C84',
    position: 'absolute',
    backgroundColor: '#ffffff',
    width: 100,
    display: 'flex',
    justifyContent: 'center',
    paddingLeft: 8,
  },
  ph: {
    left: 10,
    zIndex: 2,
    top: -32,
  },
  supportBtn: {
    alignSelf: 'flex-end',
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#fff',
    elevation: 1,
    borderRadius: 5,
    paddingHorizontal: 32,
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '40%',
    marginBottom: 16,
  },
  Tooltip: {
    backgroundColor: '#191919',
    position: 'absolute',
    height: 30,
    width: '35%',
    justifyContent: 'center',
    alignItems: 'center',
    top: 42,
    borderTopColor: '#ff444',
    borderTopWidth: 1,
  },
  pointer: {
    marginTop: 35,
    left: 10,
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: '#ff444',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 4,
    borderBottomWidth: 8,
    borderLeftWidth: 4,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'red',
    borderLeftColor: 'transparent',
    position: 'absolute',
    top: 35,
    left: 14,
  },
  countryCode: {
    width: 50,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#949494',
    fontSize: 16,
    marginRight: 16,
  },
});
